# Generated by Django 5.0.6 on 2024-07-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_sorted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255, null=True)),
                ('student_batch_name', models.CharField(max_length=255, null=True)),
                ('roll_no', models.CharField(max_length=50, null=True)),
                ('student_name', models.CharField(max_length=255, null=True)),
                ('fa_marks', models.FloatField(null=True)),
                ('sa_marks', models.FloatField(null=True)),
                ('agg_marks', models.FloatField(null=True)),
                ('rv_marks', models.FloatField(null=True)),
                ('rv_updated', models.CharField(max_length=2, null=True)),
                ('obt_grade', models.CharField(max_length=2, null=True)),
                ('course_category', models.CharField(max_length=2, null=True)),
                ('report_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
