# Generated by Django 5.0.6 on 2024-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_data_sorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_sorted',
            name='exam_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
