# Generated by Django 5.0.6 on 2024-07-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_data_sorted_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_sorted',
            name='exam_type',
        ),
    ]
