# Generated by Django 5.0.6 on 2024-07-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_remove_data_sorted_exam_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_sorted',
        ),
        migrations.DeleteModel(
            name='uploaded_data_truncated_og',
        ),
    ]
