# Generated by Django 5.0.6 on 2024-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_delete_data_sorted_delete_uploaded_data_truncated_og'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='course_category',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2),
        ),
    ]
